import Head from "next/head";
import { useSpell } from "../client";
import { withStaticCache } from "../server";

export default function Home () {
  const spellResult = useSpell("purple text in small font");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <span className={spellResult}>
          hello world
        </span>
      </main>
    </>
  );
}

export const getStaticProps = withStaticCache();
