import Head from "next/head";
import { useSpell } from "../components/Test/useSpell";

export default function Home () {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <span className={useSpell("green text in large font")}>
          hello world
        </span>
      </main>
    </>
  );
}

export const getInitialProps = async () => {
  const cacheRequest = await fetch("/spellcraft.json");
  const spellCache = await cacheRequest.json();
  return {
    spellCache
  };
};
