import Head from "next/head";
import { useSpell, withSpellStyles } from "..";
import { withStaticCache } from "../server";

export function Home () {
  const spellResult = useSpell("purple text in small font");
  // console.log({ spellResult });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <span className={spellResult}>
          hello world
        </span>
      </main>
    </>
  );
}

export default withSpellStyles(Home);

export const getStaticProps = withStaticCache();

// export const getStaticProps: GetStaticProps = async (): Promise<any> => {
//   const spellCache = readCache();
//   console.log("index.getStaticProps", { spellCache });

//   return {
//     props: {
//       a: 1,
//       spellCache
//     }
//   };
// };
